### PR TITLE
Adding CoC

### PR DESCRIPTION
**Pull request by vaishnav-mk**
Added a link to svelte's CoC.
This should resolve https://github.com/Svelte-Sirens/svelte-sirens/issues/83

### CODE REVIEW

**Review by ghostdevv — APPROVED** [review]

**Comment by spences10** [comment]
Thaks for the contribution @vaishnav-mk 👍 

LGTM 😊

This shouldn't close #84 however.

There's a `LICENCE` and `CONTRIBUTING.md` that I feel should be added at the bare minimum before that can be closed, what are your thoughts on this @ghostdevv and @brittneypostma??

**Review by spences10 — APPROVED** [review]

**Comment by ghostdevv** [comment]
I'll sort the LICENSE out in a separate PR, I can't believe we don't have one! :scream: Re: `CONTRIBUTING.md` I don't mind whether we have one or not, feel free to open a issue for that (we can do that in another PR if you get around to making an issue)

**Comment by spences10** [comment]
Yeah, sure. I think the whole reason I brought this up was that there was a bit of confusion with an initial PR from @vaishnav-mk where a `CONTRIBUTING.md` could have helped clear up any uncertainty around the contribution that was made.

**Comment by ghostdevv** [comment]
Oki we can definitely add that then, I see you mentioned it in your issue (#83) I missed that :sweat_smile: - lets do it in another PR! Happy for anyone to take that PR otherwise I will get to it end of this week

**Pull request merged**
