### PR TITLE
chore: :wrench: Use PNPM in place of npm

### LINKED ISSUE #19: Switch to PNPM
Going to make the switch over to pnpm I think.

### PR DESCRIPTION
**Pull request by spences10**
Remember to use: `rm -rf node_modules .svelte-kit pnpm-lock.yaml` when starting up the project again!

Closes #19

### CODE REVIEW

**Comment by spences10** [comment]
Good point from @ghostdevv on this not being supported by Netlify, this is more of a dev convenience though, right?

**Review by ghostdevv — COMMENTED** [review]
If we do go with this would be good to add package-lock.json to .gitignore

**Comment by ghostdevv** [comment]
@brittneypostma it's one or the other really, maintaining two package locks would be a pain. To be honest I would just stick with npm to make it easy

**Comment by brittneypostma** [comment]
Agh, okay scratch this for now 😖

**Pull request closed without merging**
