### PR TITLE
78 replaced @ aliases with $

### PR DESCRIPTION
**Pull request by vaishnav-mk**
Closes https://github.com/Svelte-Sirens/svelte-sirens/issues/78

*I'm quite new to open source so do let me know if there's anything else that should be changed for this pr to be merged!*

### CODE REVIEW

**Review by spences10 — COMMENTED** [review]
Hey @vaishnav-mk thanks for the contribution 👍 

This all LGTM but the first file I see is the `package-lock.json` was added to the `.gitignore` file, then also noticed that the `pnpm-lock.yaml` file is in there already?

Is this a preference @brittneypostma?

**Comment by spences10** [comment]
Hey @vaishnav-mk I was enquiring with @brittneypostma about it, there wasn't any need to update the file until there was a bit of clarification around what to do.

As I mentioned the `pnpm-lock.yaml` was already in there, so it may have been a good catch on your part 😃 

@brittneypostma are the lockfiles intended to be ignored?

I know there are some practices where removing them from the build is required, personally I always leave them in there as I've been burnt in the past with deps being included in the lockfiles.

Like I mentioned it's a preference and maybe something that could go into a `.github/CONTRUBUTING.md` file maybe?

**Comment by brittneypostma** [comment]
It isn't a preference and should be included for Netlify to build the site. Thanks for catching it! I think the rest of these look good as well.

**Comment by brittneypostma** [comment]
> oh lol, rookie mistake, my bad!

Are you able to remove it from the pr? I'm on mobile for now and can't fix it until later. Thank you!

**Comment by vaishnav-mk** [comment]
> > oh lol, rookie mistake, my bad!
> 
> Are you able to remove it from the pr? I'm on mobile for now and can't fix it until later. Thank you!

i've removed `pnpm-lock.yaml` from `.gitignore.`

**Comment by brittneypostma** [comment]
> > > oh lol, rookie mistake, my bad!
> > 
> > 
> > Are you able to remove it from the pr? I'm on mobile for now and can't fix it until later. Thank you!
> 
> i've removed `pnpm-lock.yaml` from `.gitignore.`

The `pnpm-lock` file is still not in, but I should be able to take care of that. Thank you for the updates. I'll merge and fix the lock issue.

**Comment by spences10** [comment]
@brittneypostma if you have any issues with git not recognising the lockfile then maybe try `git update-index --no-assume-unchanged pnpm-lock.yaml`

**Comment by spences10** [comment]
It should start tracking the file again 😊

Thanks for the contribution @vaishnav-mk 👍

**Comment by vaishnav-mk** [comment]
Oh, nice! Thanks for the opportunity, was fun making my first pr for a public project

**Comment by brittneypostma** [comment]
Should be in there now

**Pull request merged**
