### PR TITLE
Nav Update

### PR DESCRIPTION
**Pull request by ghostdevv**
Some style changes to nav, interested to see thoughts when netlify preview is up

### CODE REVIEW

**Comment by ghostdevv** [comment]
Go on the about page and scroll

**Comment by ghostdevv** [comment]
Will fix the small layout shift and lagginess if the change is liked

**Comment by brittneypostma** [comment]
> Will fix the small layout shift and lagginess if the change is liked

Yeah, I like this, I thought the lagging’s was on my end, but if that needs to be fixed then that would be good. Also, make sure it isn’t cut off on very large screens. I had a border around it before.

**Comment by ghostdevv** [comment]
Fixed it @brittneypostma

**Pull request merged**
